import streamlit as st

from app import briefs


def render():
    st.title("AI-generated policy briefs")
    st.markdown(
        "Generate a short, evidence-based brief for any country. Claude writes it using only "
        "this project's figures for that country, its misallocation score, tier rank, regional "
        "trajectory, and 2030 projection, so the brief interprets the data rather than inventing it."
    )

    if not briefs.has_api_key():
        st.warning(
            "No Anthropic API key configured. Add ANTHROPIC_API_KEY to "
            ".streamlit/secrets.toml (local) or the app's Secrets (Streamlit Cloud) "
            "to enable brief generation."
        )
        return

    country = st.selectbox("Country", briefs.country_list(), key="brief_country")
    if st.button("Generate brief", type="primary"):
        st.session_state["brief_for"] = country

    if st.session_state.get("brief_for") == country:
        try:
            with st.spinner(f"Writing a brief for {country}..."):
                text = briefs.generate_brief(country)
        except Exception as e:
            st.error(f"Brief generation failed: {e}")
            return
        with st.container(border=True):
            st.markdown(text)
        st.caption("Generated by Claude from this project's data; treat it as a draft interpretation.")
        st.download_button(
            "Download brief (Markdown)", text,
            file_name=f"brief_{country.replace(' ', '_')}.md", mime="text/markdown")import streamlit as st

from app import briefs


def render():
    st.title("AI-generated policy briefs")
    st.markdown(
        "Generate a short, evidence-based brief for any country. Claude writes it using only "
        "this project's figures for that country, its misallocation score, tier rank, regional "
        "trajectory, and 2030 projection, so the brief interprets the data rather than inventing it."
    )

    if not briefs.has_api_key():
        st.warning(
            "No Anthropic API key configured. Add ANTHROPIC_API_KEY to "
            ".streamlit/secrets.toml (local) or the app's Secrets (Streamlit Cloud) "
            "to enable brief generation."
        )
        return

    country = st.selectbox("Country", briefs.country_list(), key="brief_country")
    if st.button("Generate brief", type="primary"):
        st.session_state["brief_for"] = country

    if st.session_state.get("brief_for") == country:
        try:
            with st.spinner(f"Writing a brief for {country}..."):
                text = briefs.generate_brief(country)
        except Exception as e:
            st.error(f"Brief generation failed: {e}")
            return
        with st.container(border=True, key="card-brief"):
            st.markdown(text)
        st.caption("Generated by Claude from this project's data; treat it as a draft interpretation.")
        st.download_button(
            "Download brief (Markdown)", text,
            file_name=f"brief_{country.replace(' ', '_')}.md", mime="text/markdown")